version: '3.8'

services:
  backend:
    build:
      context: ./football-championship
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SoccerChampionship
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./football-championship-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=SoccerChampionship
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  db-data: